name: "Deploy SAM Stack to AWS"
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: for d in */ ; do cd $d && npm install --no-package-lock --loglevel=error && cd .. ; done
      - uses: r0zar/sam-deploy-action@v1.4
        env:
          TEMPLATE: "template.yaml"
          AWS_STACK_NAME: gen-conf-talks-etl
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET }}
          PARAMETER_OVERRIDES: "tokenEndpoint=${{ secrets.TOKEN_ENDPOINT }} clientId=${{ secrets.CLIENT_ID }} churchApi=${{ secrets.CHURCH_API }} clientSecret=${{ secrets.CLIENT_SECRET }} genConfTableName=${{ secrets.GEN_CONF_TABLE_NAME }} versesTableName=${{ secrets.VERSES_TABLE_NAME }} queueName=${{ secrets.QUEUE_NAME }} queueArn=${{ secrets.QUEUE_ARN }}"
