name: "Production ETL pipeline"
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: for d in */ ; do cd $d && npm install --no-package-lock --loglevel=error && cd .. ; done
      - uses: r0zar/sam-deploy-action@v1.4
        env:
          TEMPLATE: "template.yaml"
          AWS_STACK_NAME: lds-church-api-etl-production
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
          AWS_DEPLOY_BUCKET: ${{ secrets.AWS_DEPLOY_BUCKET_PROD }}
          PARAMETER_OVERRIDES: "tokenEndpoint=${{ secrets.TOKEN_ENDPOINT_PROD }} clientId=${{ secrets.CLIENT_ID_PROD }} churchApi=${{ secrets.CHURCH_API_PROD }} clientSecret=${{ secrets.CLIENT_SECRET_PROD }} genConfTableName=${{ secrets.GEN_CONF_TABLE_NAME }} versesTableName=${{ secrets.VERSES_TABLE_NAME }} queueName=${{ secrets.QUEUE_NAME_PROD }} queueArn=${{ secrets.QUEUE_ARN_PROD }}"
